=== Priyanka-Pruthi/XML/lms.dtd
<!ELEMENT LMS (Users,Courses,Assessments,Reports)>
<!ELEMENT Student (#PCDATA)>
<!ATTLIST Student StudentId ID #REQUIRED
                  Name CDATA #REQUIRED
                  Email CDATA #REQUIRED
                  EnrollmentDate CDATA #REQUIRED>

                  
<!ELEMENT Instructor (#PCDATA)>
 <!ATTLIST Instructor InstructorId ID #REQUIRED
                    Name CDATA #REQUIRED
                    Email CDATA #REQUIRED>
               
<!ELEMENT Admin (#PCDATA)>
<!ATTLIST Admin AdminId ID #REQUIRED 
                Name CDATA #REQUIRED
                Email CDATA #REQUIRED>  
                
<!ELEMENT Manager (Reports*)>
<!ATTLIST Manager ManagerId ID #REQUIRED Name CDATA #REQUIRED
Email CDATA #REQUIRED>   

<!ELEMENT Users (Student*, Instructor*, Admin*, Manager*)>

<!ELEMENT Courses (Course*)>
<!ELEMENT Course (Content*)>
<!ATTLIST Course CourseId ID #REQUIRED 
                 Title CDATA #REQUIRED
                 Desription CDATA #REQUIRED>

<!ELEMENT Content (#PCDATA)>
<!ATTLIST Content contentId ID #REQUIRED
                  Type CDATA #REQUIRED
                   URL CDATA #REQUIRED>
                 
 <!ELEMENT Assessments (Assessment*)>    
 <!ELEMENT Assessment (Questions*)>
 <!ATTLIST Assessment  AssessmentId ID #REQUIRED
                       CourseId CDATA #REQUIRED>

 <!ELEMENT Questions (Question*)>
 <!ELEMENT Question (Options+,Answer?)>
 <!ATTLIST Question QuestionId ID #REQUIRED 
                    Text CDATA #REQUIRED>

 <!ELEMENT Options (Option*)>
 <!ELEMENT Option (#PCDATA)>
 <!ATTLIST Option OptionId ID #REQUIRED 
                    Text CDATA #REQUIRED>

 <!ELEMENT Answer (#PCDATA)>
 
 <!ELEMENT Reports (Report*)>
 <!ELEMENT Report (#PCDATA)>
 <!ATTLIST Report ReportId ID #REQUIRED 
                    ReportType CDATA #REQUIRED
                    GeneratedDate CDATA #REQUIRED
                    DATA CDATA #REQUIRED
                    ManagerId CDATA #REQUIRED>

=== Priyanka-Pruthi/XML/LMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LMS SYSTEM "lms.dtd">
<LMS>
    <Users>
        <Student StudentId="S1" Name="Zeal" Email="Zeal@gmail.com" EnrollmentDate="2024-08-05"/>
        <Instructor InstructorId="I1" Name="Priyanka" Email="p@gmail.com"/>
        <Admin AdminId="A1" Name="Palash" Email="p1@gmail.com"/>
        <Manager ManagerId="M1" Name="Mita" Email="m@gmail.com">
            <Reports>
                <Report ReportId="R1" ReportType="Pending_Learning" GeneratedDate="2024-08-01" DATA="some list" ManagerId="M1"/>
                <Report ReportId="R2" ReportType="New_Learning_Registeration" GeneratedDate="2024-08-05" DATA="some list" ManagerId="M1"/>
            </Reports>
        </Manager>
    </Users>
    <Courses>
        <Course CourseId="C1" Title="Learn HTML" Desription="Markup Language">
            <Content contentId="CN1" Type="Video" URL="https://example.com"></Content>
            <Content contentId="CN2" Type="InstructorLed" URL="https://example.com"></Content>
        </Course>
        <Course CourseId="C2" Title="Learn HTML and CSS" Desription="Markup Language"/>    
   </Courses>
   <Assessments>
     <Assessment AssessmentId="Assessment1" CourseId="C1">
        <Questions>
            <Question QuestionId="Q1" Text="What is HTML">
                <Options>
                    <Option OptionId="Q1_A1" Text="MarkUp Language"></Option>
                    <Option OptionId="Q1_A2" Text="Programming Language"></Option>
                </Options>
                <Answer>
                    <![CDATA[Q1_A1]]>
                </Answer>
            </Question>
            <Question QuestionId="Q2" Text="Types of CSS">
                <Options>
                    <Option OptionId="Q2_A1" Text="inline"></Option>
                    <Option OptionId="Q2_A2" Text="internal"></Option>
                    <Option OptionId="Q2_A3" Text="external"></Option>
                    <Option OptionId="Q2_A4" Text="All"></Option>
                </Options>
                <Answer>
                    <![CDATA[Q2_A4]]>
                </Answer>
            </Question>
        </Questions>
     </Assessment>
   </Assessments>
 
    <Reports>
        <Report ReportId="R3" ReportType="Pending_Learning" GeneratedDate="2024-08-01" DATA="some list" ManagerId="M1"/>
        <Report ReportId="R4" ReportType="New_Learning_Registeration" GeneratedDate="2024-08-05" DATA="some list" ManagerId="M1"/>
    </Reports>
   
</LMS>
